# Generated by Django 6.1 on 2026-08-20 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_category_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
