# Generated by Django 6.1 on 2026-08-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_rename_create_at_category_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
