# Generated by Django 6.1 on 2026-08-19 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aboutUs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={"verbose_name_plural": "Abouts"},
        ),
    ]
