# Generated by Django 6.1 on 2026-08-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aboutUs", "0002_alter_about_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform_name", models.CharField(max_length=50)),
                ("platform_link", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField()),
            ],
        ),
    ]
